security:
    password_hashers:
        App\Entity\System\AdminUser:
            algorithm: auto

    providers:
        admin_users:
            entity:
                class: App\Entity\System\AdminUser
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            lazy: true
            provider: admin_users
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: admin_dashboard
                enable_csrf: true
            logout:
                path: admin_logout
                target: admin_login

        main:
            lazy: true

    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            App\Entity\System\AdminUser:
                algorithm: plaintext
